---
all:
  children:
    linux:
      hosts:
        wireguard_server:
          ansible_ssh_host: 192.168.120.247
          ansible_user: root
      vars:
        ansible_python_interpreter: /usr/bin/python3