- hosts: linux
  become: true
  pre_tasks:
  - name: Update and Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  tasks:
  - name: Install packages
    package:
      name:
        - git
        - htop
        - vim
        - curl
        - net-tools
        - telnet
        - tree
        - docker
        - docker-compose

  - name: Add user to the Docker group.
    user:
      name: ec2-user
      groups: docker
      append: yes

  - name: Restart docker daemon
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker

  - name: Create the wireguard directory
    ansible.builtin.file:
      path: /opt/wireguard
      state: directory
      mode: '0755'

  - name: Copy Docker-Compose file
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/../wireguard/docker-compose.yml"
      dest: /opt/wireguard
      owner: root
      group: root
      mode: '0644'
      backup: yes

  - name: Start wireguard
    docker_compose:
      project_src: /opt/wireguard
      recreate: always